apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

namePrefix: asset-service-

commonLabels:
  app: asset-service
  service: asset-service

resources:
- ../base

images:
- name: service
  newName: ghcr.io/CHANGEME/asset-service
  newTag: latest

configMapGenerator:
- name: service-config
  behavior: merge
  literals:
  - SERVICE_NAME=asset-service
