apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

namePrefix: graphics-gateway-

commonLabels:
  app: graphics-gateway
  service: graphics-gateway

resources:
- ../base

images:
- name: service
  newName: ghcr.io/CHANGEME/graphics-gateway
  newTag: latest

configMapGenerator:
- name: service-config
  behavior: merge
  literals:
  - SERVICE_NAME=graphics-gateway
