apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

namePrefix: text-gateway-

commonLabels:
  app: text-gateway
  service: text-gateway

resources:
- ../base

images:
- name: service
  newName: ghcr.io/CHANGEME/text-gateway
  newTag: latest

configMapGenerator:
- name: service-config
  behavior: merge
  literals:
  - SERVICE_NAME=text-gateway
