apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

namePrefix: auth-

commonLabels:
  app: auth-service
  service: auth-service

resources:
- ../base

images:
- name: service
  newName: ghcr.io/CHANGEME/auth-service
  newTag: latest

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "128Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "256Mi"
  target:
    kind: Deployment

configMapGenerator:
- name: service-config
  behavior: merge
  literals:
  - SERVICE_NAME=auth-service
