apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

namePrefix: persistence-service-

commonLabels:
  app: persistence-service
  service: persistence-service

resources:
- ../base

images:
- name: service
  newName: ghcr.io/CHANGEME/persistence-service
  newTag: latest

configMapGenerator:
- name: service-config
  behavior: merge
  literals:
  - SERVICE_NAME=persistence-service
