apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

namePrefix: script-executor-

commonLabels:
  app: script-executor
  service: script-executor

resources:
- ../base

images:
- name: service
  newName: ghcr.io/CHANGEME/script-executor
  newTag: latest

configMapGenerator:
- name: service-config
  behavior: merge
  literals:
  - SERVICE_NAME=script-executor
