apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

namePrefix: physics-service-

commonLabels:
  app: physics-service
  service: physics-service

resources:
- ../base

images:
- name: service
  newName: ghcr.io/CHANGEME/physics-service
  newTag: latest

configMapGenerator:
- name: service-config
  behavior: merge
  literals:
  - SERVICE_NAME=physics-service
